# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.ref == 'main' && 'production' || 'staging' }}

    defaults:
      run:
        shell: bash

    steps:
    # Step 1: Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SECRETS }}

    # Step 3: Debug Azure Secrets
    - name: Debug Azure Secrets
      run: |
        echo "Tenant ID: $AZURE_TENANT_ID"
        echo "Client ID: $AZURE_CLIENT_ID"
        echo "Subscription ID: $AZURE_SUBSCRIPTION_ID"

    # Step 4: Set up Python for Checkov
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Step 5: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    # Step 6: Install Checkov
    - name: Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov
        checkov --version  # Verify Checkov is installed

    # Step 7: Create .checkov.yml file to skip specific checks globally
    - name: Create .checkov.yml file
      run: |
        echo 'skip-checks:' > .checkov.yml
        echo '  - CKV_AZURE_1  # Skipping HTTPS enforcement on Azure Storage Accounts' >> .checkov.yml
        echo '  - CKV_AZURE_2  # Skipping Azure resource tagging enforcement' >> .checkov.yml
        echo '  - CKV_AZURE_3  # Skipping unnecessary public exposure of Azure resources' >> .checkov.yml

    # Step 8: Run Checkov to scan the Terraform code (skipping failed checks)
    - name: Run Checkov
      run: checkov -d . --config-file .checkov.yml || true  # Skips failed checks based on .checkov.yml

    # Step 9: Install TFLint
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --version  # Verify TFLint is installed

    # Step 10: Run TFLint to lint Terraform files
    - name: Run TFLint
      run: tflint || true  # If you want the pipeline to fail on issues, remove "|| true"

    # Step 11: Terraform Init
    - name: Terraform Init
      run: terraform init

    # Step 12: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan.binary

    # Step 13: Terraform Show
    # Convert the Terraform binary plan to JSON for Infracost
    - name: Terraform Show
      run: terraform show -json tfplan.binary > plan.json

    # Step 14: Install Infracost
    - name: Install Infracost
      run: |
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
        infracost --version  # Verify Infracost is installed

    # Step 15: Configure Infracost API key
    - name: Configure Infracost API key
      run: infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}

    # Step 16: Run Infracost to calculate costs
    - name: Run Infracost
      run: |
        infracost breakdown --path=plan.json \
        --format=json --out-file=infracost-report.json

    # Step 17: Post Infracost comment to PR (if applicable)
    - name: Post Infracost Comment
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        infracost comment github --path=infracost-report.json \
        --repo=$GITHUB_REPOSITORY \
        --pull-request=$GITHUB_REF_NAME \
        --github-token=${{ secrets.GITHUB_TOKEN }}

    # Step 18: Terraform Apply for dev (No approval needed)
    - name: Terraform Apply - dev
      if: github.ref == 'refs/heads/dev'
      run: terraform apply -auto-approve -input=false

    # Step 19: Terraform Apply for QA (Approval Required)
    - name: Terraform Apply - qa
      if: github.ref == 'refs/heads/qa'
      environment:
        name: qa
        url: ${{ steps.deploy.outputs.app_url }}
      approvals:
        required: 1
      run: terraform apply -auto-approve -input=false

    # Step 20: Terraform Apply for production (Approval Required)
    - name: Terraform Apply - production
      if: github.ref == 'refs/heads/production'
      environment:
        name: production
        url: ${{ steps.deploy.outputs.app_url }}
      approvals:
        required: 1
      run: terraform apply -auto-approve -input=false
